name: Playwright Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            my-vite-app/node_modules
            playwright/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: |
          cd my-vite-app && npm install
          cd ../playwright && npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('playwright/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-
          
      - name: Install Playwright Browsers
        run: |
          cd playwright
          npx playwright install --with-deps

      - name: Kill any process using port 5173
        run: |
          sudo lsof -t -i:5173 | xargs sudo kill -9 || true

      - name: Run React app
        run: |
          cd my-vite-app
          npm run dev & npx wait-on http://localhost:5173 --timeout 60000

      - name: Wait for React app to be ready
        run: npx wait-on http://localhost:5173 --timeout 60000

      - name: Run Playwright tests
        run: |
          cd playwright
          npm run test
        continue-on-error: true 

      - name: Cache test results
        uses: actions/cache@v3
        with:
          path: playwright/test-results
          key: ${{ runner.os }}-test-results-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-test-results-

      - name: Upload test results
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: playwright/test-results
